FROM google/cloud-sdk

COPY docker/deploy-helper/deploy_to_kubernetes.sh /deploy/deploy_to_kubernetes.sh
COPY docker/deploy-helper/deploy_to_kubernetes.sh /deploy/deploy_to_kubernetes.sh
COPY docker/deploy-helper/templater.sh /deploy/templater.sh
